name: stokey_fe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # http:
  model: ^0.1.3
  smooth_star_rating: 1.1.1
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/stokeyimage_drawer.png
    - assets/stokeyimage_logo.png
    - assets/stokeyimage_wishlist.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/vegetable.png
    - assets/fruits.png
    - assets/Electronic.png
    - assets/Health and beauty.png
    - assets/Chocolate.png
    - assets/Grocerys.png
    - assets/exclusive offer for you 01.png
    - assets/exclusive offer for you 02.png
    - assets/exclusive offer for you 03.png
    - assets/exclusive offer for you 04.png
    - assets/slide 01.png
    - assets/slide 02.png
    - assets/slide 03.png
    - assets/slide 04.png
    - assets/slide 05.png
    - assets/Best Sellers.png
    - assets/Group 681.png
    - assets/heart bottun.png
    - assets/heart bottun.png
    - assets/10.jpg
    - assets/11.jpg
    - assets/12.png
    - assets/13.jpg
    - assets/14.jpg
    - assets/wishlistfilled.png
    - assets/arrowleft.png
    - assets/stokey.png
    - assets/tomato.png
    - assets/garlic.jpeg
    - assets/ladyfinger.png
    - assets/broccoli.png
    - assets/eggplant.png
    - assets/carrot.png
    - assets/profile1.png
    - assets/profile3.png
    - assets/profile4.png
    - assets/coins.png
    - assets/RateUs.png
    - assets/location.jpg
    - assets/bismi.jpg
    - assets/wemart.png
    - assets/metfresh.png
    - assets/grenfood.png
    - assets/bloomsberry.jpg
    - assets/mymarket.png
    - assets/gstore.jpg
    - assets/fresh.jpg
    - assets/grenfood.png
    - assets/kmart.jpeg
    - assets/fruits1.jpg
    - assets/clothing3.png
    - assets/veg2.png
    - assets/cosmetics2.jpg
    - assets/electro2.png
    - assets/groceries1.png
    - assets/meat1.png
    - assets/dairy1.jpg
    - assets/meat2.jpg
    - assets/dairy2.png
    - assets/loc.png

    
  
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
